# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "HoBeom"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
max_results: 10
max_qa_num: 2

publish_readme: True
publish_gitpage: True

keywords:
    "Action Recognition":
        queries: ["action recognition", "action classification", "action detection", "action segmentation", "temporal action localization"]
        md_readme_path: 'arxiv/action-recognition/README.md'
        json_readme_path: 'arxiv/action-recognition/data.json'
        qa_json_path: 'arxiv/action-recognition/qa.json'
    "Human Pose Estimation":
        queries: ["human pose estimation", "pose estimation", "keypoint detection", "keypoint estimation", "pose detection"]
        md_readme_path: 'arxiv/human-pose-estimation/README.md'
        json_readme_path: 'arxiv/human-pose-estimation/data.json'
        qa_json_path: 'arxiv/human-pose-estimation/qa.json'
