# TODO: add papers by configuration file
user_name: "HoBeom"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
max_results: 10
max_qa_num: 2

publish_readme: True
publish_gitpage: True

keywords:
    "Action Recognition":
        queries: ["action recognition", "action classification", "action detection", "action segmentation", "temporal action localization"]
        md_readme_path: 'arxiv/action-recognition/README.md'
        json_readme_path: 'arxiv/action-recognition/data.json'
        qa_json_path: 'arxiv/action-recognition/qa.json'
    "Human Pose Estimation":
        queries: ["human pose estimation", "pose estimation", "keypoint detection", "keypoint estimation", "pose detection"]
        md_readme_path: 'arxiv/human-pose-estimation/README.md'
        json_readme_path: 'arxiv/human-pose-estimation/data.json'
        qa_json_path: 'arxiv/human-pose-estimation/qa.json'
    "Theory of Mind":
        queries: ["theory of mind", "ToM", "social reasoning", "mental state modeling"]
        md_readme_path: 'arxiv/theory-of-mind/README.md'
        json_readme_path: 'arxiv/theory-of-mind/data.json'
        qa_json_path: 'arxiv/theory-of-mind/qa.json'
    "Dialogue Agents":
        queries: ["collaboration agent", "communication agent", "dialogue agent"]
        md_readme_path: 'arxiv/dialogue-agents/README.md'
        json_readme_path: 'arxiv/dialogue-agents/data.json'
        qa_json_path: 'arxiv/dialogue-agents/qa.json'
    "Robot & Agent":
        queries: ["Embodied Agent", "Robot Learning", "Robot Policy", "Robot Policies", "Human-Robot", "Cross-Embodiment"]
        md_readme_path: 'arxiv/robot-agent/README.md'
        json_readme_path: 'arxiv/robot-agent/data.json'
        qa_json_path: 'arxiv/robot-agent/qa.json'
    "Vision Language Action Model":
        queries: ["Vision-Language-Action Model", "Vision Language Action Model", "VLA Model", "VLA Models"]
        md_readme_path: 'arxiv/vla-model/README.md'
        json_readme_path: 'arxiv/vla-model/data.json'
        qa_json_path: 'arxiv/vla-model/qa.json'
